NameAPI/profile-project-alfie/bo/urls.py
from django.urls import path
from . import views, movies

app_name = 'bo' 

urlpatterns = [
    path('',views.View.as_view()),
    path('user/',views.View.as_view(), name='user'),
    path('user/list/',views.Transact.as_view(), name='user-list'),
    path('user/save/<int:pk>/',views.Transact.as_view(), name='user-save'),
    path('movies/',movies.Movies.as_view(), name='movies'),



]

NameAPI/profile-project-alfie/profiler/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',include('register.urls')),
    path('bo/',include('bo.urls')),
    
]

NameAPI/profile-project-alfie/register/urls.py
from django.urls import include, path
from . import views
from rest_framework.routers import DefaultRouter

app_name = 'register' 

router = DefaultRouter()
router.register('', views.ViewRP, basename="RP")

urlpatterns = [
    path('',views.Signup.as_view()),
    path('user', include(router.urls)),
    path('signup/',views.Signup.as_view(), name = 'signup'),
    # path('save/',views.Save.as_view(), name = 'save'),
]

NameAPI/profile-project-alfie/bo/models.py
from django.db import models

# Create your models here.

NameAPI/profile-project-alfie/register/models.py
from django.db import models
from bo.common import MReference

# class MReference(models.Model):
#     reference_id = models.BigIntegerField(primary_key=True)
#     reference_group = models.CharField(max_length=100)
#     reference_code = models.CharField(max_length=20)
#     reference_shortdesc = models.CharField(max_length=100)
#     reference_longdesc = models.CharField(
#                             max_length=200,
#                             null=True,
#                             blank=True,
#                             default=None  
#                             )
#     reference_desc = models.CharField(max_length=500)
#     reference_groupcode = models.CharField(
#                             max_length=20,
#                             null=True,
#                             blank=True,
#                             default=None                            
#                             )
#     reference_tablestatus_id = models.BigIntegerField()
#     date_added = models.DateTimeField(auto_now_add=True)
#     addedby_user_id = models.BigIntegerField()
#     updatedby_user_id = models.BigIntegerField(
#         null=True,
#         blank=True
#     )
#     date_updated = models.DateTimeField(
#         null=True,
#         blank=True,
#         default=None
#     )

class MUser(models.Model):
    user_id = models.BigIntegerField(primary_key=True)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=10, null=True, blank=True)
    email = models.CharField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=500, null=True, blank=True)
    momo = models.CharField(max_length=500, null=True, blank=True)
    password = models.CharField(max_length=500, null=True, blank=True)
    reference_tablestatus_fk = models.ForeignKey(MReference, on_delete=models.PROTECT, related_name="muser_tablestatus", default=1)
    date_added = models.DateTimeField(auto_now_add=True)
    addedby_user_id = models.BigIntegerField(default=1)
    updatedby_user_id = models.BigIntegerField(
        null=True,
        blank=True
    )
    date_updated = models.DateTimeField(
        null=True,
        blank=True,
        default=None
    )    

class rafflePeople(models.Model):
    firstName = models.CharField(max_length=100, null=True, default='', blank=True)
    lastName = models.CharField(max_length=100, null=True, default='', blank=True)
    age=models.IntegerField(null=True, default='', blank=True)
    birthday=models.CharField(max_length=100, null=True, default='', blank=True)
    address = models.CharField(max_length=1000, null=True, default='', blank=True)
    sex=models.CharField(max_length=10, null=True, default='', blank=True)
    contactNumber=models.CharField(max_length=20, null=True, default='', blank=True)
    lokal=models.CharField(max_length=40, null=True, default='', blank=True)
    data_created=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.firstName

NameAPI/profile-project-alfie/bo/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from django.shortcuts import render
from django.http import Http404
from django.views.generic import (TemplateView)
from django.db import transaction
from django.db.models import Value
from django.db.models.functions import Concat
from register.models import MUser
from register.serializers import UserSerializer
from .common import Repeated                            
import datetime
import json

class View(TemplateView):
    template_name='user/user.html'

class Transact(APIView):
    '''
        Author: Armando Garing II
        Date Created: Sept. 06, 2021
        Purpose: Responsible for user search
    '''    
    # permission_classes = (IsAuthenticated,)
    def get(self, request, format=None):
        value = Repeated()
        list_data={}
        result_data = {}

        search_value = request.GET.get('search_value', '')

        queryset = MUser.objects.annotate(
                                    search=Concat('firstname',Value(' '),'lastname')).filter(
                                    search__icontains=search_value) 
                                    
        list_data= queryset.values('user_id'
                        ,'firstname'
                        ,'lastname'
                        ,'reference_tablestatus_fk'                        
                        ,'reference_tablestatus_fk__reference_longdesc')
                                                                                                
        # return Response(list_data)
        if len(list_data):
            result_data['code'] = status.HTTP_200_OK
            result_data['message'] = value.http_message(status.HTTP_200_OK)
        else:
            result_data['code'] = status.HTTP_204_NO_CONTENT
            result_data['message'] = value.http_message(status.HTTP_204_NO_CONTENT)

        result_data['data'] = list_data

        return Response(result_data, status=status.HTTP_201_CREATED)      

    def get_object(self, pk):
        try:
            return MUser.objects.get(user_id=pk)
        except MUser.DoesNotExist:
            raise Http404  
   

    def put(self, request, pk, format=None):
        value = Repeated()
        user_id = self.get_object(pk)
        result = {}

        data = json.dumps(request.data)
        form = json.loads(data)

        form['user_id'] = user_id
        form['date_updated'] = datetime.datetime.now()

        serialize = UserSerializer(user_id, data=form)
        if serialize.is_valid():
            serialize.save()

            result['data'] = serialize.data
            result['code'] = status.HTTP_200_OK
            result['message'] = value.http_message(status.HTTP_200_OK)            
            return Response(result, status=status.HTTP_201_CREATED)
        return Response(serialize.errors, status=status.HTTP_400_BAD_REQUEST)         

NameAPI/profile-project-alfie/register/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import (TemplateView)
from django.db import transaction
from .serializers import UserSerializer, rpSerializer
from .models import MUser, rafflePeople
from rest_framework import viewsets
import json                                

class Signup(TemplateView):
    template_name='signup/signup.html'   

class ViewRP(viewsets.ModelViewSet):
    queryset = rafflePeople.objects.all()
    serializer_class = rpSerializer

NameAPI/profile-project-alfie/bo/templates/base/layout_bo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block stylesheet %}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
        <title>Back Office</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="{% static 'css/base/layout_bo.css' %}">
    {% endblock %}
</head>
<body>
    <ul>
        <li><a class="active" href="{% url 'bo:user' %}">User</a></li>
        <li><a href="{% url 'bo:movies' %}">Movies</a></li>
        {% comment %} <li><a href="#contact">Contact</a></li>
        <li><a href="#about">About</a></li>  {% endcomment %}
    </ul>
    {% block content %}

    {% endblock %}
    {% block javascript %}
    
        <script src="{% static 'js/external/common.js' %}"></script>
        <script src="{% static 'js/layout/layout_bo.js' %}"></script>
        
        
    {% endblock %}
</body>
</html>

NameAPI/profile-project-alfie/bo/templates/movies/movies.html
{% extends "base/layout_bo.html" %}
{% load static %}


{% block content %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/movies/movies.css' %}" />

<h1>Movies</h1>
    
{% endblock %}

{% block javascript %}
    {{ block.super }}
    
    <script src="{% static 'js/movies/movies.js' %}"></script>
{% endblock %}

NameAPI/profile-project-alfie/bo/templates/user/user.html
{% extends "base/layout_bo.html" %}
{% load static %}


{% block content %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/user/user.css' %}" />

<div class="col-md-12">
    <h1>User</h1>
    <div class="card">
        <div class="card-body">
            <form id="form-search">
                <div class="row">
                    <div class="col">
                        <div class="form-row">
                            <div class="col">
                                <input type="text" class="form-control" name="search-value" placeholder="Enter user">
                            </div>
                        </div>                        
                    </div>
                    <div class="col">
                        <button class="btn btn-outline-primary btn-search" type="button">Search</button>
                        <button class="btn btn-outline-secondary btn-new" type="button">New </button>
                        <button class="btn btn-outline-success" type="button">Clear</button>                                        
                    </div>
                  </div>                
            </form>
        </div>
    </div>
    <div class="card mt-1">
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="tbl-user">
                    <tr>
                        <th scope="row">1</th>
                        <td>John</td>
                        <td>Doe</td>
                        <td>jdoe@gmail.com</td>
                        <td>
                            <button class="btn btn-outline-info" type="button">Edit</button>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Will</td>
                        <td>Johnson</td>
                        <td>will@yahoo.com</td>
                        <td>
                            <button class="btn btn-outline-info" type="button">Edit</button>
                        </td>                        
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>Shannon</td>
                        <td>Williams</td>
                        <td>shannon@yahoo.com</td>
                        <td>
                            <button class="btn btn-outline-info" type="button">Edit</button>
                        </td>                        
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- MODAL -->
<div class="modal" id="modal-user">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Modal Title</h5>
            <button class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            <form id="modal-form-user">
                <div class="form-group">
                    <label for="firstname">Firstname</label>
                    <input class="form-control" type="text" name="firstname" placeholder="Enter Firstname">
                </div>                
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn btn-outline-success btn-save" type="button">Save</button>
            <button class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    
    <script src="{% static 'js/user/user.js' %}"></script>
{% endblock %}

NameAPI/profile-project-alfie/register/templates/base/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block stylesheet %}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
        <title>Bootstrap Simple Registration Form</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="{% static 'css/base/layout.css' %}">
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    {% block javascript %}
        <script src="{% static 'js/external/common.js' %}"></script>
        <script src="{% static 'js/user/user.js' %}"></script>
        <script src="{% static 'js/layout/layout.js' %}"></script>
        
        
    {% endblock %}
</body>
</html>

NameAPI/profile-project-alfie/register/templates/signup/signup.html
{% extends "base/layout.html" %}
{% load static %}


{% block content %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/signup/signup.css' %}" />
<div class="signup-form">
    <form id="frm-customer">
		<h2>Register</h2>
		<p class="hint-text">Create your account. It's free and only takes a minute.</p>
        <div class="form-group">
			<div class="row">
				<div class="col"><input type="text" class="form-control" id="fname" name="firstname" placeholder="First Name" required="required"></div>
				<div class="col"><input type="text" class="form-control" id="lname" name="lastname" placeholder="Last Name" required="required"></div>
			</div>        	
        </div>
        <div class="form-group">
        	<input type="text" class="form-control" id="username" placeholder="Email" required="required">
        </div>        
        <div class="form-group">
        	<input type="email" class="form-control" id="email" name="email" placeholder="Email" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" id="password" name="password" placeholder="Password" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" id="confirm-pass" name="confirm_pass" placeholder="Confirm Password" required="required">
        </div>        
        <div class="form-group">
			<label class="form-check-label"><input type="checkbox" id="terms" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
		</div>
		<div class="form-group">
            <button type="button" id="btn-save" class="btn btn-success btn-lg btn-block">Register Now</button>
        </div>
    </form>
	<div class="text-center">Already have an account? <a href="#">Sign in</a></div>
</div>


{% endblock %}

{% block javascript %}
    {{ block.super }}
    
    <script src="{% static 'js/signup/signup.js' %}"></script>
{% endblock %}